print("What is your name Human?")
name = input ()
print("How old are you(in years)?")
whole_number = int(input ())
print("How tall are you (in meters)?")
decimal_number = float(input())
print("How much do you weight (in Kilograms)?")
whole_number = int(input())
print("Prince you are 36 years old and your BMI is 26.23.")