print("What is your name Human?")
name = input (Prins)
print("How old are you(in years)?")
whole_number = int(input (36))
print("How tall are you (in meters)?")
decimal_number = float(input(1.80))
print("How much do you weight (in Kilograms)?")
whole_number = int(input(85))
name = input ( Prins )
