print("please enter the number of lives")
whole_number = int(input())
print("Please enter the energy level")
whole_number = int(input())
print("please enter the shield level")
whole_number = int(input())
print("Health has been set.")
print("Health: ") 
print("Energy:U0002666")
print("Shield:")