print("please enter the number of lives.")
lives = int(input())
print("Please enter the energy level")
energy = int(input())
print("please enter the shield level")
shield = int(input())
print("Health has been set.")
print("lives:"+ lives *"\u2665")
print("Energy:"+energy*"\u2666")
print("Shield:"+shield*"\u2666")