print("please enter the number of lives")
whole_number = int(input(3))
print("Please enter the energy level")
whole_number = int(input(10))
print("please enter the shield level")
whole_number = int(input(7))
print("Health has been set.")
print("Lives  ")